package br.com.fiap.challengeaguiabranca.ui.theme

import androidx.compose.ui.graphics.Color

// Paleta InnovateCorp — alinhada ao web-preview/src/theme.css
val InnovatePrimary = Color(0xFF6D5DFC)
val InnovatePrimaryDark = Color(0xFF5746D8)
val InnovatePrimaryLight = Color(0xFFA29BFE)
val InnovateBackground = Color(0xFFF7F5F0)
val InnovateBackgroundDark = Color(0xFF11110F)
val InnovateSurface = Color(0xFFFFFFFF)
val InnovateSurfaceDark = Color(0xFF1B1A17)
val InnovateSurface2 = Color(0xFFF2EFE7)
val InnovateSurface2Dark = Color(0xFF24221F)
val InnovateOnPrimary = Color(0xFFFFFFFF)
val InnovateTextPrimary = Color(0xFF1F1F1D)
val InnovateTextPrimaryDark = Color(0xFFF6F1E8)
val InnovateTextSecondary = Color(0xFF6F6B63)
val InnovateTextSecondaryDark = Color(0xFFB9B1A4)
val InnovateTextTertiary = Color(0xFF9B958A)
val InnovateLink = Color(0xFF4F46E5)
val InnovateLinkDark = Color(0xFFA5B4FC)
val InnovateOperatorBlue = Color(0xFF3B82F6)
val InnovateOperatorBlueDark = Color(0xFF1D4ED8)
val InnovateManagerPink = Color(0xFFEC4899)
val InnovateManagerPinkDark = Color(0xFFB91C4D)
val InnovateLeaderPurple = Color(0xFF7C3AED)
val InnovateLeaderPurpleDark = Color(0xFF4F1D96)
val InnovateSuccess = Color(0xFF10B981)
val InnovateWarning = Color(0xFFF59E0B)
val InnovateError = Color(0xFFEF4444)
val InnovateBorder = Color(0xFFE3DED4)
val InnovateBorderDark = Color(0xFF34312B)
val InnovateLogoBackground = Color(0xFFFFE8D5)
val InnovateLogoForeground = Color(0xFF9A3412)
